task:
  name: CI
  freebsd_instance:
    image_family: freebsd-13-2
  go_modules_cache:
    folder: .gomodcache
  setup_script:
    - pkg install -y git-lite go golangci-lint
    - go env -w GOMODCACHE=$(pwd)/.gomodcache
    - go mod download
    - go install github.com/google/go-licenses@latest
    - sudo touch /etc/pf.conf
    - echo 'pf_enable="YES"' | sudo tee -a /etc/rc.conf
    - sudo service pf start
  build_script:
    - make
  test_script:
    - make test
    - make lint
    - PATH="${PATH}:${HOME}/go/bin" make verify-notice
  integ_script:
    - sudo make install
    - make integ-test
