task:
  name: CI
  freebsd_instance:
    image_family: freebsd-13-0
  setup_script:
    - pkg install -y git-lite go golangci-lint protobuf
    - go mod download
    - ./script/install-dev-tools.sh
    - ./script/setup-cirrus.sh
  build_script:
    - make -C "$(go env GOPATH)/src/go.sbk.wtf/runj" protos
    - git status --porcelain
    - make
  test_script:
    - make test
    - make lint
  integ_script:
    - sudo make install
    - make integ-test
